version: 0.2

env:
    variables:
        CACHE_CONTROL: "6400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 18
    commands:
        - npm install -g @angular/cli
pre-build:
    commands:
        - npm run build --prod
build:
    commands:
        - npm install 
        - npm run build --prod
artifacts:
    files:
        - '**/*'
    base-directory: arn:aws:codeartifact:eu-west-1:471956150795:repository/admtc-dist/ADMTC-V2-Dist
    discard-paths: yes