import { TranslateService } from '@ngx-translate/core';
import { Component, Input, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { RNCPTitlesService } from 'app/service/rncpTitles/rncp-titles.service';
import { cloneDeep } from 'lodash';

export interface ClassTaskStatus {
  _id: string;
  name: string;
  is_task_builder_selected: boolean;
  is_task_builder_generated: boolean;
  is_all_task_builder_published: boolean;
  parent_rncp_title: {
    _id: string;
  };
}

@Component({
  selector: 'ms-title-manager-tasks',
  templateUrl: './title-manager-tasks.component.html',
  styleUrls: ['./title-manager-tasks.component.scss'],
})
export class TitleManagerTasksComponent implements OnInit {
  @Input() rncpId: string;
  @Input() classId: string;
  @Input() subtab: string;
  tabs: string[] = ['autogeneratedtask', 'previewoftask'];
  currentIndex = 0;
  isClassAutoTaskGenerated: boolean = false;
  classTaskStatus: ClassTaskStatus;

  constructor(private rncpTitleService: RNCPTitlesService) {}

  ngOnInit() {
    if (this.subtab) {
      this.goToTab(this.subtab);
    }

    this.getClassGenerationStatus();
  }

  getClassGenerationStatus() {
    if (!this.classId) return;
    this.rncpTitleService.getClassAutomaticTask(this.classId).subscribe((resp) => {
      if (resp) {
        this.classTaskStatus = cloneDeep(resp);
      }
    });
  }

  goToTab(tabName: string) {
    this.currentIndex = this.tabs.findIndex((tab) => tab === tabName);

  }
}
